#ifndef			_HEAD_FILE_DEFINE_H_
#define		_HEAD_FILE_DEFINE_H_

#include <QTabWidget>
#include <QTableView>
#include <QTreeWidget>
#include <QButtonGroup>
#include <QGraphicsView>
#include <QBoxLayout>
#include <QHeaderView>
#include <QTableWidget>
#include <QListWidget>
#include <QTabBar>
#include <QToolButton>
#include<QScreen>
#include <QDebug>
#include <QTimer>
#include <QProcess>
#include <QHeaderView>

#include <QLabel>
#include <QGridLayout>
#include <QApplication>
#include <QLineEdit>
#include <QTextEdit>
#include <QWidget>
#include <QLabel>
#include <QFileDialog>
#include <QStackedWidget>
#include <QCoreApplication>
#include <QPropertyAnimation>
#include <QEvent>
#include <QPainter>
#include<QGraphicsSceneMouseEvent>
#include<QGraphicsRectItem>
#include <QDebug>
#include <QKeyEvent>
#include <QDockWidget>
#include <QGraphicsItem>
#include <QMdiSubWindow>
#include <QUndoStack>
#include <QMdiArea>
#include <QPropertyAnimation>
#include <QStackedLayout>
#include <QVBoxLayout>
#include <QMessageBox>
#include <QWidgetAction>
#include <QFileDialog>
#include <QDesktopWidget>
#include <QInputDialog>
#include <QApplication>
#include <QPushButton>
#include <QCoreApplication>
#include <QToolTip>
#include <QDateTime>
#include <QTimer>
#include <QtMath>
 #include <QEvent>
#include <QMenu>
#include <QAction>
#include <QActionGroup>
#include <QKeyEvent>
#include <QToolTip>
#include <QAction>
#include <QDockWidget>
#include <QDir>
#include <QDesktopServices>
#include <QMutexLocker>
#include <QMutex>
#include <QCheckBox>
#include <QWidget>
#include <QToolBar>
#include <QMenuBar>
#include <QLabel>
#include <QStackedWidget>
#include <QCoreApplication>
#include <QPropertyAnimation>
#include <QListView>
#include <QPainter>
#include <QPropertyAnimation>
#include <QStackedLayout>
#include <QVBoxLayout>
#include <QToolButton>
#include <QFileDialog>
#include <QFileInfo>
#include <QTableWidget>
#include <QProgressBar>
#include <QRadioButton>
#include <QXmlStreamWriter>
#include <QPalette>
#include <QFileIconProvider>
#include <QTextBrowser>
#include <QThread>
#include <QSplitter>
#include <iostream>
#include <map>
#include <memory>
#include <algorithm>
#include <string>
#include <vector>
#include <sstream>

#endif//_HEAD_FILE_DEFINE_H_
